---
title: "Lab 6"
author: "Jacob Sturges"
date: "6/17/2019"
output: 
  html_document:
    toc: yes
    toc_float: yes
    theme: spacelab
    highlights: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Task 1

```{r}
getwd()
```

# Task 2

## Plot 4 normal curves

```{r}
layout(matrix(1:4, nr = 2, nc = 2, byrow = TRUE))
curve(dnorm(x, mean=10, sd=4), xlim = c(-10, 30))
curve(dnorm(x, mean=10, sd=2), xlim = c(0, 20))
curve(dnorm(x, mean=5, sd=10), xlim = c(-30, 40))
curve(dnorm(x, mean=5, sd=1/2), xlim = c(2, 8))
```

## Plot 4 regions and probabilities

```{r}
layout(matrix(1:4, nr = 2, nc = 2, byrow = TRUE))
curve(dnorm(x, mean = 0, sd = 1), xlim = c(-5,5))
prob=1-pnorm(2,mean=0,sd=1)
prob=round(prob,4)
xcurve=seq(2,3,length=1000)
ycurve=dnorm(xcurve,mean=0,sd=1)
polygon(c(2,xcurve,3),c(0,ycurve,0),col="Red")
text(x=-2, y=0.1, paste("Area = ", prob, sep=" "))

curve(dnorm(x, mean=4,sd=2),xlim=c(-5,10))
prob=pnorm(5,mean=4,sd=2)-pnorm(1,mean=4,sd=2)
prob=round(prob,4)
xcurve=seq(1,5,length=1000)
ycurve=dnorm(xcurve,mean=4,sd=2)
polygon(c(1,xcurve,5),c(0,ycurve,0),col="Red")
text(x=0, y=0.1, paste("Area = ", prob, sep=" "))

curve(dnorm(x, mean=10,sd=4),xlim=c(-10,25))
prob=pnorm(9,mean=10,sd=4)
prob=round(prob,4)
xcurve=seq(0,9,length=1000)
ycurve=dnorm(xcurve,mean=10,sd=4)
polygon(c(0,xcurve,9),c(0,ycurve,0),col="Red")
text(x=1, y=0.05, paste("Area = ", prob, sep=" "))

curve(dnorm(x, mean=-2,sd=0.5),xlim=c(-5,0))
prob=pnorm(-2,mean=-2,sd=1/2)-pnorm(-3,mean=-2,sd=1/2)
prob=round(prob,4)
xcurve=seq(-3,-2,length=1000)
ycurve=dnorm(xcurve,mean=-2,sd=0.5)
polygon(c(-3,xcurve,-2),c(0,ycurve,0),col="Red")
text(x=-3, y=0.5, paste("Area = ", prob, sep=" "))
```

# Task 3

## Plot gamma curves

```{r}
layout(matrix(1:4, nr = 2, nc = 2, byrow = TRUE))
curve(dgamma(x,shape=1,scale=1),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2, ylab="Gamma density", main="Beta=1")
text(x=6,y=0.5,paste("alpha=",1))

curve(dgamma(x,shape=3,scale=1),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2, ylab="Gamma density", main="Beta=1")
text(x=6,y=0.5,paste("alpha=",3))

curve(dgamma(x,shape=5,scale=1),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2, ylab="Gamma density", main="Beta=1")
text(x=6,y=0.5,paste("alpha=",5))
```

## Plot gamma regions and probabilities

```{r}
layout(matrix(1:4, nr = 2, nc = 2, byrow = TRUE))
curve(dgamma(x,shape=3,scale=2),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2, ylab="Gamma density", main="Beta=2")
text(x=7,y=0.4,paste("alpha=",3))
prob=pgamma(5,shape=3,scale=2)-pgamma(2,shape=3,scale=2)
prob=round(prob,4)
xcurve=seq(2,5,length=1000)
ycurve=dgamma(xcurve,shape = 5, scale = 1)
polygon(c(2,xcurve,5), c(0,ycurve,0), col = "Red")
text(x=3.5, y=0.8, paste("Area = ", prob, sep=" "))

curve(dgamma(x,shape=6,scale=3),xlim=c(0,10),ylim=c(0,0.02),col="Red",lwd=2, ylab="Gamma density", main="Beta=3")
text(x=7,y=0.007,paste("alpha=",6))
prob=pgamma(4,shape=6,scale=3)-pgamma(0,shape=6,scale=3)
prob=round(prob,4)
xcurve=seq(1,4,length=1000)
ycurve=dgamma(xcurve,shape = 6, scale = 3)
polygon(c(1,xcurve,4), c(0,ycurve,0), col = "Red")
text(x=3.3, y=0.015, paste("Area = ", prob, sep=" "))

curve(dgamma(x,shape=2,scale=4),xlim=c(0,10),ylim=c(0,0.25),col="Red",lwd=2, ylab="Gamma density", main="Beta=4")
text(x=7,y=0.1,paste("alpha=",2))
prob=pgamma(6,shape=2,scale=4)-pgamma(3,shape=2,scale=4)
prob=round(prob,4)
xcurve=seq(3,6,length=1000)
ycurve=dgamma(xcurve,shape = 2, scale = 4)
polygon(c(3,xcurve,6), c(0,ycurve,0), col = "Red")
text(x=3.3, y=0.2, paste("Area = ", prob, sep=" "))
```

# Task 4

## Plot the chi-sq distributions

```{r}
layout(matrix(1:4, nr = 2, nc = 2, byrow = TRUE))
curve(dchisq(x,df=1),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2,
ylab="Chisq density", main="df=1,5")
text(x=5,y=0.5,paste("df=",1))

curve(dchisq(x,df=2),xlim=c(0,5),ylim=c(0,1),col="Red",lwd=2,
ylab="Chisq density", main="df=2,5")
text(x=3,y=0.7,paste("df=",2))

curve(dchisq(x,df=4),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2,
ylab="Chisq density", main="df=4,5")
text(x=5,y=0.5,paste("df=",4))

curve(dchisq(x,df=20),xlim=c(0,40),ylim=c(0,0.1),col="Red",lwd=2,
ylab="Chisq density", main="df=20,5")
text(x=5,y=0.04,paste("df=",20))
```

## Plot chi-sq regions and probabilities

```{r}
layout(matrix(1:4, nr = 2, nc = 2, byrow = TRUE))
curve(dchisq(x,df=2),xlim=c(0,5),ylim=c(0,1),col="Red",lwd=2,
ylab="Chisq density", main="P(2 <= Y <= 4)")
text(x=4,y=0.3,paste("df=",2))
prob=pchisq(4,df=2)-pchisq(2,df=2)
prob=round(prob,4)
xcurve=seq(2,4,length=1000)
ycurve=dchisq(xcurve,df=2)
polygon(c(2,xcurve,4), c(0,ycurve,0), col = "Red")
text(x=2, y=0.75, paste("Area = ", prob, sep=" "))

curve(dchisq(x,df=3),xlim=c(0,5),ylim=c(0,1),col="Red",lwd=2,
ylab="Chisq density", main="P(3 <= Y <= 5)")
text(x=4,y=0.35,paste("df=",3))
prob=pchisq(5,df=3)-pchisq(3,df=3)
prob=round(prob,4)
xcurve=seq(3,5,length=1000)
ycurve=dchisq(xcurve,df=3)
polygon(c(3,xcurve,5), c(0,ycurve,0), col = "Red")
text(x=2, y=0.75, paste("Area = ", prob, sep=" "))

curve(dchisq(x,df=20),xlim=c(0,40),ylim=c(0,0.1),col="Red",lwd=2,
ylab="Chisq density", main="P(10 < Y <= 21)")
text(x=30,y=0.03,paste("df=",20))
prob=pchisq(21,df=20)-pchisq(10,df=20)
prob=round(prob,4)
xcurve=seq(10,21,length=1000)
ycurve=dchisq(xcurve,df=20)
polygon(c(10,xcurve,21), c(0,ycurve,0), col = "Red")
text(x=15, y=0.08, paste("Area = ", prob, sep=" "))
```

# Task 5

## Plot weibull regions and probabilities

```{r}
layout(matrix(1:4, nr = 2, nc = 2, byrow = TRUE))
curve(dweibull(x,shape=3,scale=2),xlim=c(0,5),ylim=c(0,1),col="Red",lwd=2, ylab="Weibull density", main="Beta=2")
text(x=4,y=0.4,paste("alpha=",3))
prob=pweibull(5,shape=3,scale=2)-pweibull(2,shape=3,scale=2)
prob=round(prob,4)
xcurve=seq(2,5,length=1000)
ycurve=dweibull(xcurve,shape = 3, scale = 2)
polygon(c(2,xcurve,5), c(0,ycurve,0), col = "Red")
text(x=2, y=0.8, paste("Area = ", prob, sep=" "))

curve(dweibull(x,shape=1,scale=1),xlim=c(0,5),ylim=c(0,1),col="Red",lwd=2, ylab="Weibull density", main="Beta=1")
text(x=4,y=0.4,paste("alpha=",1))
prob=pweibull(2,shape=3,scale=2)-pweibull(1,shape=3,scale=2)
prob=round(prob,4)
xcurve=seq(1,2,length=1000)
ycurve=dweibull(xcurve,shape = 1, scale = 1)
polygon(c(1,xcurve,2), c(0,ycurve,0), col = "Red")
text(x=2, y=0.8, paste("Area = ", prob, sep=" "))

curve(dweibull(x,shape=4,scale=4),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2, ylab="Weibull density", main="Beta=4")
text(x=7,y=0.4,paste("alpha=",4))
prob=pweibull(4,shape=3,scale=2)-pweibull(2,shape=3,scale=2)
prob=round(prob,4)
xcurve=seq(2,4,length=1000)
ycurve=dweibull(xcurve,shape = 4, scale = 4)
polygon(c(2,xcurve,4), c(0,ycurve,0), col = "Red")
text(x=3.5, y=0.8, paste("Area = ", prob, sep=" "))
```

# Task 6

## Investigate beta distribution 0 <= Y <= 1

```{r}
curve(dbeta(x,shape1=2,shape2=3),xlim=c(0,1))
```

## Plot beta regions and probabilities

```{r}
layout(matrix(1:4, nr = 2, nc = 2, byrow = TRUE))
curve(dbeta(x,shape1=2,shape2=3),xlim=c(0,1),col="Blue",lwd=2, ylab="Beta density")
prob=pbeta(0.4,shape1=2,shape2=3)-pbeta(0.1,shape1=2,shape2=3)
prob=round(prob,4)
xcurve=seq(0.1,0.4,length=1000)
ycurve=dbeta(xcurve,shape1 = 2, shape2 = 3)
polygon(c(0.1,xcurve,0.4), c(0,ycurve,0), col = "Red")
text(x=0.5, y=0.7, paste("Area = ", prob, sep=" "))

curve(dbeta(x,shape1=2,shape2=2),xlim=c(0,1),col="Blue",lwd=2, ylab="Beta density")
prob=pbeta(0.4,shape1=2,shape2=2)-pbeta(0.1,shape1=2,shape2=2)
prob=round(prob,4)
xcurve=seq(0.1,0.4,length=1000)
ycurve=dbeta(xcurve,shape1 = 2, shape2 = 2)
polygon(c(0.1,xcurve,0.4), c(0,ycurve,0), col = "Red")
text(x=0.5, y=0.7, paste("Area = ", prob, sep=" "))

curve(dbeta(x,shape1=6,shape2=4),xlim=c(0,1),col="Blue",lwd=2, ylab="Beta density")
prob=pbeta(0.8,shape1=6,shape2=4)-pbeta(0.5,shape1=6,shape2=4)
prob=round(prob,4)
xcurve=seq(0.5,0.8,length=1000)
ycurve=dbeta(xcurve,shape1 = 6, shape2 = 4)
polygon(c(0.5,xcurve,0.8), c(0,ycurve,0), col = "Red")
text(x=0.5, y=0.7, paste("Area = ", prob, sep=" "))
```

# Task 7

```{r}
library(MATH4753Stur)
myncurve(mu=10,sigma=5,a=6)
```

